name: Update time

on:
  schedule:
    - cron: '* * * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Change
        run: date -R > README.md

      - name: Commit
        run: |
          git config --global user.email "actions@example.com"
          git config --global user.name "Github Action"
          git commit -am .

      - name: Push
        run: git push
